// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/takuya-go-kit/go-jwtkit"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GenerateTokenPair provides a mock function for the type MockService
func (_mock *MockService) GenerateTokenPair(ctx context.Context, userID uuid.UUID, role string) (*jwtkit.TokenPair, error) {
	ret := _mock.Called(ctx, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokenPair")
	}

	var r0 *jwtkit.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*jwtkit.TokenPair, error)); ok {
		return returnFunc(ctx, userID, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *jwtkit.TokenPair); ok {
		r0 = returnFunc(ctx, userID, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwtkit.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, userID, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GenerateTokenPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokenPair'
type MockService_GenerateTokenPair_Call struct {
	*mock.Call
}

// GenerateTokenPair is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - role string
func (_e *MockService_Expecter) GenerateTokenPair(ctx interface{}, userID interface{}, role interface{}) *MockService_GenerateTokenPair_Call {
	return &MockService_GenerateTokenPair_Call{Call: _e.mock.On("GenerateTokenPair", ctx, userID, role)}
}

func (_c *MockService_GenerateTokenPair_Call) Run(run func(ctx context.Context, userID uuid.UUID, role string)) *MockService_GenerateTokenPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_GenerateTokenPair_Call) Return(tokenPair *jwtkit.TokenPair, err error) *MockService_GenerateTokenPair_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockService_GenerateTokenPair_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, role string) (*jwtkit.TokenPair, error)) *MockService_GenerateTokenPair_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshTokens provides a mock function for the type MockService
func (_mock *MockService) RefreshTokens(ctx context.Context, refreshTokenString string) (*jwtkit.TokenPair, error) {
	ret := _mock.Called(ctx, refreshTokenString)

	if len(ret) == 0 {
		panic("no return value specified for RefreshTokens")
	}

	var r0 *jwtkit.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*jwtkit.TokenPair, error)); ok {
		return returnFunc(ctx, refreshTokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *jwtkit.TokenPair); ok {
		r0 = returnFunc(ctx, refreshTokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwtkit.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshTokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_RefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshTokens'
type MockService_RefreshTokens_Call struct {
	*mock.Call
}

// RefreshTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshTokenString string
func (_e *MockService_Expecter) RefreshTokens(ctx interface{}, refreshTokenString interface{}) *MockService_RefreshTokens_Call {
	return &MockService_RefreshTokens_Call{Call: _e.mock.On("RefreshTokens", ctx, refreshTokenString)}
}

func (_c *MockService_RefreshTokens_Call) Run(run func(ctx context.Context, refreshTokenString string)) *MockService_RefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RefreshTokens_Call) Return(tokenPair *jwtkit.TokenPair, err error) *MockService_RefreshTokens_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockService_RefreshTokens_Call) RunAndReturn(run func(ctx context.Context, refreshTokenString string) (*jwtkit.TokenPair, error)) *MockService_RefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAccessToken provides a mock function for the type MockService
func (_mock *MockService) RevokeAccessToken(ctx context.Context, accessTokenString string) error {
	ret := _mock.Called(ctx, accessTokenString)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAccessToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, accessTokenString)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RevokeAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAccessToken'
type MockService_RevokeAccessToken_Call struct {
	*mock.Call
}

// RevokeAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - accessTokenString string
func (_e *MockService_Expecter) RevokeAccessToken(ctx interface{}, accessTokenString interface{}) *MockService_RevokeAccessToken_Call {
	return &MockService_RevokeAccessToken_Call{Call: _e.mock.On("RevokeAccessToken", ctx, accessTokenString)}
}

func (_c *MockService_RevokeAccessToken_Call) Run(run func(ctx context.Context, accessTokenString string)) *MockService_RevokeAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RevokeAccessToken_Call) Return(err error) *MockService_RevokeAccessToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RevokeAccessToken_Call) RunAndReturn(run func(ctx context.Context, accessTokenString string) error) *MockService_RevokeAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllForUser provides a mock function for the type MockService
func (_mock *MockService) RevokeAllForUser(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RevokeAllForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllForUser'
type MockService_RevokeAllForUser_Call struct {
	*mock.Call
}

// RevokeAllForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) RevokeAllForUser(ctx interface{}, userID interface{}) *MockService_RevokeAllForUser_Call {
	return &MockService_RevokeAllForUser_Call{Call: _e.mock.On("RevokeAllForUser", ctx, userID)}
}

func (_c *MockService_RevokeAllForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_RevokeAllForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RevokeAllForUser_Call) Return(err error) *MockService_RevokeAllForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RevokeAllForUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockService_RevokeAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function for the type MockService
func (_mock *MockService) RevokeRefreshToken(ctx context.Context, refreshTokenString string) error {
	ret := _mock.Called(ctx, refreshTokenString)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, refreshTokenString)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type MockService_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshTokenString string
func (_e *MockService_Expecter) RevokeRefreshToken(ctx interface{}, refreshTokenString interface{}) *MockService_RevokeRefreshToken_Call {
	return &MockService_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", ctx, refreshTokenString)}
}

func (_c *MockService_RevokeRefreshToken_Call) Run(run func(ctx context.Context, refreshTokenString string)) *MockService_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RevokeRefreshToken_Call) Return(err error) *MockService_RevokeRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RevokeRefreshToken_Call) RunAndReturn(run func(ctx context.Context, refreshTokenString string) error) *MockService_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function for the type MockService
func (_mock *MockService) ValidateAccessToken(ctx context.Context, tokenString string) (*jwtkit.CustomClaims, error) {
	ret := _mock.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *jwtkit.CustomClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*jwtkit.CustomClaims, error)); ok {
		return returnFunc(ctx, tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *jwtkit.CustomClaims); ok {
		r0 = returnFunc(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwtkit.CustomClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockService_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockService_Expecter) ValidateAccessToken(ctx interface{}, tokenString interface{}) *MockService_ValidateAccessToken_Call {
	return &MockService_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", ctx, tokenString)}
}

func (_c *MockService_ValidateAccessToken_Call) Run(run func(ctx context.Context, tokenString string)) *MockService_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ValidateAccessToken_Call) Return(customClaims *jwtkit.CustomClaims, err error) *MockService_ValidateAccessToken_Call {
	_c.Call.Return(customClaims, err)
	return _c
}

func (_c *MockService_ValidateAccessToken_Call) RunAndReturn(run func(ctx context.Context, tokenString string) (*jwtkit.CustomClaims, error)) *MockService_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRefreshToken provides a mock function for the type MockService
func (_mock *MockService) ValidateRefreshToken(ctx context.Context, tokenString string) (*jwtkit.CustomClaims, error) {
	ret := _mock.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRefreshToken")
	}

	var r0 *jwtkit.CustomClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*jwtkit.CustomClaims, error)); ok {
		return returnFunc(ctx, tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *jwtkit.CustomClaims); ok {
		r0 = returnFunc(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwtkit.CustomClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ValidateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRefreshToken'
type MockService_ValidateRefreshToken_Call struct {
	*mock.Call
}

// ValidateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockService_Expecter) ValidateRefreshToken(ctx interface{}, tokenString interface{}) *MockService_ValidateRefreshToken_Call {
	return &MockService_ValidateRefreshToken_Call{Call: _e.mock.On("ValidateRefreshToken", ctx, tokenString)}
}

func (_c *MockService_ValidateRefreshToken_Call) Run(run func(ctx context.Context, tokenString string)) *MockService_ValidateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ValidateRefreshToken_Call) Return(customClaims *jwtkit.CustomClaims, err error) *MockService_ValidateRefreshToken_Call {
	_c.Call.Return(customClaims, err)
	return _c
}

func (_c *MockService_ValidateRefreshToken_Call) RunAndReturn(run func(ctx context.Context, tokenString string) (*jwtkit.CustomClaims, error)) *MockService_ValidateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
