all: false
force-file-write: true
formatter: goimports
log-level: info
template: testify

packages:
  github.com/takuya-go-kit/go-jwtkit:
    interfaces:
      RevocationStore:
        config:
          dir: "mock"
          filename: "RevocationStore.go"
          pkgname: "mock"
          structname: "MockRevocationStore"

      Service:
        config:
          dir: "mock"
          filename: "Service.go"
          pkgname: "mock"
          structname: "MockService"
